import { getSession } from 'next-auth/client'
import Head from 'next/head'
import Feed from '../components/Feed';
import Header from '../components/Header'
import Login from "../components/Login"
import Posts from '../components/Posts';
import Sidebar from '../components/Sidebar';


export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by Sumit " />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex bg-gray-100">
        {/* sidebar */}
        <Sidebar />
        <Feed />
        {/* feed */}
        {/* widget */}
      </main>

    </div>
  )
}


export async function getServerSideProps(context) {
  // Get the user
  const session = await getSession(context)

  return {
    props: {
      session
    }
  }
}